services:
  mssql:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=Test1234
      - DEV_USER=dev
    volumes:
      - mssql-volume:/var/opt/mssql
      - ./src:/src
    restart: unless-stopped
volumes:
  mssql-volume:
